export const DATA = [
  {
    createdAt: new Date("2024-05-01T12:30:00Z"),
    amount: 132,
    description: "spent on food",
    tags: ["fast food"],
    type: "expense",
  },
  {
    createdAt: new Date("2024-05-02T08:15:00Z"),
    amount: 50,
    description: "bought groceries",
    tags: ["groceries"],
    type: "expense",
  },
  {
    createdAt: new Date("2024-05-03T18:45:00Z"),
    amount: 200,
    description: "paid electricity bill",
    tags: ["utilities"],
    type: "expense",
  },
  {
    createdAt: new Date("2024-05-04T14:00:00Z"),
    amount: 75,
    description: "monthly internet subscription",
    tags: ["utilities", "internet"],
    type: "expense",
  },
  {
    createdAt: new Date("2024-05-05T09:30:00Z"),
    amount: 15,
    description: "morning coffee",
    tags: ["beverages"],
    type: "expense",
  },
  {
    createdAt: new Date("2024-05-06T11:00:00Z"),
    amount: 120,
    description: "dinner with friends",
    tags: ["dining out"],
    type: "expense",
  },
  {
    createdAt: new Date("2024-05-07T13:20:00Z"),
    amount: 40,
    description: "gym membership",
    tags: ["fitness"],
    type: "expense",
  },
  {
    createdAt: new Date("2024-05-08T17:50:00Z"),
    amount: 60,
    description: "new book",
    tags: ["education", "books"],
    type: "expense",
  },
  {
    createdAt: new Date("2024-05-09T20:15:00Z"),
    amount: 35,
    description: "cinema tickets",
    tags: ["entertainment"],
    type: "expense",
  },
  {
    createdAt: new Date("2024-05-10T16:45:00Z"),
    amount: 25,
    description: "bought a gift",
    tags: ["gifts"],
    type: "expense",
  },
];
